IGI/LR5/VeterinaryClinc/VeterinaryClinc/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from VeterinaryClinc import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('clients/', include('clients.urls')),
    path('appointments/', include('appointments.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('articles/', include('chart_django_project.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/VeterinaryClinc/appointments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('doctors_schedule/', views.doctors_schedule, name="doctors_schedule"),
    path('order_create/', views.order_create, name='order_create'),
    path('orders', views.order_list, name='order_list'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
    path('orders/<int:pk>/update/', views.order_update, name='order_update'),
    path('orders/<int:pk>/delete/', views.order_delete, name='order_delete'),
    path('order/pay/<int:order_id>/', views.order_pay, name='order_pay'),

    path('<int:pk>/', views.service_detail, name='service_detail'),
    path('create/', views.service_create, name='service_create'),
    path('', views.service_list, name='service_list'),
    path('<int:pk>/update/', views.service_update, name='service_update'),
    path('<int:pk>/delete/', views.service_delete, name='service_delete'),
]

IGI/LR5/VeterinaryClinc/main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('cat_fact', views.cat_fact_view, name='cat_fact'),
    path('random_dog', views.random_dog_view, name='random_dog'),
    path('questions/', views.questions_list, name='questions_list'),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('vacancies/', views.VacancyListView.as_view(), name='vacancy-list'),
    path('vacancies/<int:pk>/', views.VacancyDetailView.as_view(), name='vacancy-detail'),
    path('promocodes/', views.promocode_list, name='promocode-list'),
    path('reviews/', views.reviews_list, name='reviews-list'),
    path('add_review/', views.add_review, name='add_review'),
    path('policy/', views.policy, name='policy'),
    path('partners/', views.partner_list, name='partner_list')
]

IGI/LR5/VeterinaryClinc/appointments/models.py
from asyncio.windows_events import NULL

from django.db import models
from django.db.models import Sum
from django.urls import reverse

from clients.models import Pet
from users.models import Client, Doctor

from main.models import PromoCode


class ServiceCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


class Service(models.Model):
    name = models.CharField(max_length=255)
    cost = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE, related_name='services')


    def __str__(self):
        return f'{self.name} costs {self.cost}'

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='appointments')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='appointments')
    date = models.DateField()
    services = models.ManyToManyField(Service, through='OrderService')
    total_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    is_payed = models.BooleanField(default=False)  # Новое поле
    def __str__(self):
        return f'{self.date}'

    def save(self, *args, **kwargs):
        discount = 1.0
        if self.pk:
            if self.client.promocode:
                try:
                    promo = PromoCode.objects.get(promocode=self.client.promocode)
                    discount = (self.total_cost * promo.percent) / 100
                except PromoCode.DoesNotExist:
                    pass

            self.total_cost = self.services.aggregate(total=Sum('cost'))['total'] or 0.00
            if self.client.promocode is not NULL:
                discount = (self.total_cost * promo.percent) / 100
                self.total_cost -= discount

        super().save(*args, **kwargs)

class OrderService(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

IGI/LR5/VeterinaryClinc/appointments/forms.py
from django import forms
from .models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'cost', 'category']

IGI/LR5/VeterinaryClinc/appointments/views.py
import datetime
import logging

from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render, redirect
from .models import Service, ServiceCategory, Order, OrderService
from .forms import ServiceForm
from clients.models import Pet

from users.models import Doctor
from users.models import Client
logging.basicConfig(level=logging.INFO, filename="py_log.log",filemode="w",
                    format="%(asctime)s %(levelname)s %(message)s")
@login_required
def doctors_schedule(request):
    logging.info("Обращение к doctors_schedule")
    doctor = request.user.doctor
    orders_before_today = Order.objects.filter(doctor=doctor, date__lt=datetime.date.today())
    orders_today = Order.objects.filter(doctor=doctor, date=datetime.date.today())
    orders_tomorrow = Order.objects.filter(doctor=doctor, date=datetime.date.today() + datetime.timedelta(days=1))
    orders_after_tomorrow = Order.objects.filter(doctor=doctor,
                                                 date__gt=datetime.date.today() + datetime.timedelta(days=1))

    context = {
        'doctor': doctor,
        'orders_before_today': orders_before_today,
        'orders_today': orders_today,
        'orders_tomorrow': orders_tomorrow,
        'orders_after_tomorrow': orders_after_tomorrow,
    }
    logging.info("Возврат страницы")
    return render(request, 'doctors_schedule.html', context)
@login_required
def order_create(request):
    logging.info("Обращение к order_create")
    if request.method == 'POST':
        client = request.user.client
        pet_id = request.POST.get('pet')
        doctor_id = request.POST.get('doctor')
        date = request.POST.get('date')
        service_ids = request.POST.getlist('services')

        pet = client.pet_set.get(id=pet_id)
        doctor = Doctor.objects.get(id=doctor_id)
        services = Service.objects.filter(id__in=service_ids)  # Извлечь все услуги одним запросом
        total_cost = services.aggregate(Sum('cost'))['cost__sum'] or 0  # Рассчитать общую стоимость
        order = Order.objects.create(client=client, pet=pet, doctor=doctor, date=date, total_cost=total_cost)

        # Создать связи OrderService для всех выбранных услуг
        OrderService.objects.bulk_create(
            [OrderService(order=order, service=service) for service in services]
        )
        logging.info("Обращение прошло успешно")
        return redirect('order_list')
    else:
        client = request.user.client
        pets = client.pet_set.all()
        doctors = Doctor.objects.all()
        services = Service.objects.all()
        logging.info("метод не POST")
        return render(request, 'order_create.html', {'pets': pets, 'doctors': doctors, 'services': services})


@login_required
def order_list(request):
    logging.info("Обращение к order_list")
    orders = Order.objects.filter(client=request.user.client)
    return render(request, 'order_list.html', {'orders': orders})


@login_required
def order_detail(request, pk):
    logging.info("Обращение к order_detail")
    order = get_object_or_404(Order, pk=pk)
    order = Order.objects.get(id=pk)
    return render(request, 'order_detail.html', {'order': order})


@login_required
def order_update(request, pk):
    logging.info("Обращение к order_update")
    order = get_object_or_404(Order, pk=pk)
    order = Order.objects.get(id=pk)
    if request.method == 'POST':
        pet_id = request.POST.get('pet')
        doctor_id = request.POST.get('doctor')
        date = request.POST.get('date')
        service_ids = request.POST.getlist('services')

        pet = Pet.objects.get(id=pet_id)
        doctor = Doctor.objects.get(id=doctor_id)
        order.pet = pet
        order.doctor = doctor
        order.date = date
        order.save()

        order.services.clear()
        for service_id in service_ids:
            service = Service.objects.get(id=service_id)
            OrderService.objects.create(order=order, service=service)

        return redirect('order_list')
    else:
        client = request.user.client
        pets = client.pet_set.all()
        doctors = Doctor.objects.all()
        services = Service.objects.all()
        return render(request, 'order_update.html', {'order': order, 'pets': pets, 'doctors': doctors, 'services': services})


@login_required
def order_delete(request, pk):
    logging.info("Обращение к order_delete")
    order = get_object_or_404(Order, pk=pk)
    order = Order.objects.get(id=pk)
    order.delete()
    return redirect('order_list')


@login_required
def service_detail(request, pk):
    logging.info("Обращение к service_detail")
    service = Service.objects.get(id=pk)
    return render(request, 'service_detail.html', {'service': service})

@login_required
def service_create(request):
    logging.info("Обращение к service_create")
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('service_list')
    else:
        form = ServiceForm()
    return render(request, 'service_create.html', {'form': form})

@login_required
def service_list(request):
    logging.info("Обращение к service_list")
    services = Service.objects.all()
    return render(request, 'service_list.html', {'services': services})


@login_required
def service_update(request, pk):
    logging.info("Обращение к service_update")
    service = get_object_or_404(Service, pk=pk)
    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            form.save()
            return redirect('service_list')
    else:
        form = ServiceForm(instance=service)
    return render(request, 'service_update.html', {'form': form})


@login_required
def service_delete(request, pk):
    logging.info("Обращение к service_delete")
    service = get_object_or_404(Service, pk=pk)
    if request.method == 'POST':
        service.delete()
        return redirect('service_list')
    return render(request, 'service_delete.html', {'service': service})

@login_required
def order_pay(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    # Здесь добавьте логику для перехода на страницу оплаты
    if request.method == 'POST':
        # Логика успешной оплаты
        order.is_payed = True
        order.save()
        return redirect('order_list')  # Перенаправьте на страницу с заказами

    return render(request, 'pay.html', {'order': order})

IGI/LR5/VeterinaryClinc/appointments/templates/doctors_schedule.html
{% extends 'main/layout.html' %}

{% block content %}
  <h1>Doctor Orders</h1>

  <h2>Doctor Name: {{ doctor.last_name }}</h2>

  <h3>Orders Before Today</h3>
 {% if orders_before_today %}
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Client</th>
        <th>Pet</th>
        <th>Services</th>
        <th>Total Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders_before_today %}
        <tr>
          <td>{{ order.date }}</td>
          <td>{{ order.client.last_name }} {{ order.client.first_name }}</td>
          <td>{{ order.pet.name }}</td>
          <td>
            {% for service in order.services.all %}
              {{ service.name }} - {{ service.cost }}<br>
            {% endfor %}
          </td>
          <td>{{ order.total_cost }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>У вас еще не было заказов раньше</p>
  {% endif %}

  <h3>Orders Today</h3>
 {% if orders_today %}
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Client</th>
        <th>Pet</th>
        <th>Services</th>
        <th>Total Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders_today %}
        <tr>
          <td>{{ order.date }}</td>
          <td>{{ order.client.last_name }} {{ order.client.first_name }}</td>
          <td>{{ order.pet.name }}</td>
          <td>
            {% for service in order.services.all %}
              {{ service.name }} - {{ service.cost }}<br>
            {% endfor %}
          </td>
          <td>{{ order.total_cost }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>У вас нет заказов на сегодня</p>
  {% endif %}

  <h3>Orders Tomorrow</h3>
 {% if orders_tomorrow %}
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Client</th>
        <th>Pet</th>
        <th>Services</th>
        <th>Total Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders_tomorrow %}
        <tr>
          <td>{{ order.date }}</td>
          <td>{{ order.client.last_name }} {{ order.client.first_name }}</td>
          <td>{{ order.pet.name }}</td>
          <td>
            {% for service in order.services.all %}
              {{ service.name }} - {{ service.cost }}<br>
            {% endfor %}
          </td>
          <td>{{ order.total_cost }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>У вас нет заказов на сегодня</p>
  {% endif %}

 {% if orders_after_tomorrow %}
  <h3>Orders After Tomorrow</h3>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Client</th>
        <th>Pet</th>
        <th>Services</th>
        <th>Total Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders_after_tomorrow %}
        <tr>
          <td>{{ order.date }}</td>
          <td>{{ order.client.last_name }} {{ order.client.first_name }}</td>
          <td>{{ order.pet.name }}</td>
          <td>
            {% for service in order.services.all %}
              {{ service.name }} - {{ service.cost }}<br>
            {% endfor %}
          </td>
          <td>{{ order.total_cost }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>У вас нет заказов на следующие дни</p>
  {% endif %}
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/order_create.html
{% extends 'main/layout.html' %}

{% block content %}
  <h1>Добавить в корзину</h1>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="pet">Питомец:</label>
      <select name="pet" id="pet">
        {% for pet in pets %}
          <option value="{{ pet.id }}">{{ pet.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="doctor">Доктор:</label>
      <select name="doctor" id="doctor">
        {% for doctor in doctors %}
          <option value="{{ doctor.id }}">{{ doctor.last_name }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="date">Дата:</label>
      <input type="date" name="date" id="date">
    </div>
    <div>
      <label>Услуги:</label>
      {% for service in services %}
        <div>
          <input type="checkbox" name="services" value="{{ service.id }}">
          <label>{{ service.name }} - {{ service.cost }}</label>
        </div>
      {% endfor %}
    </div>
    <button type="submit">Создать заказ</button>
  </form>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/order_detail.html
{% extends 'main/layout.html' %}

{% block content %}
  <h1>Детали заказа</h1>
  <p>Дата: {{ order.date }}</p>
  <p>Питомец: {{ order.pet.name }}</p>
  <p>Доктор: {{ order.doctor.name }}</p>
  <h2>Услуги</h2>
  <ul>
    {% for service in order.services.all %}
      <li>{{ service.name }} - {{ service.cost }}</li>
    {% endfor %}
  </ul>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/order_list.html
{% extends 'main/layout.html' %}

{% block content %}
 <a href="{% url 'order_create' %}">Добавить</a>
  <h1>Корзина заказов</h1>
  <table border="1">
    <thead>
      <tr>
        <th>Дата</th>
        <th>Питомец</th>
        <th>Доктор</th>
        <th>Общая стоимость</th>
        <th colspan="4">Действия с заказом</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
        <tr>
          <td>{{ order.date }}</td>
          <td>{{ order.pet.name }}</td>
          <td>{{ order.doctor.last_name }}</td>
          <td>{{ order.total_cost}}</td>
          <td><a href="{% url 'order_detail' order.id %}">Посмотреть</a></td>
          <td><a href="{% url 'order_update' order.id %}">Изменить </a></td>
          <td><a href="{% url 'order_delete' order.id %}">Удалить</a></td>
          <td>
                {% if order.is_payed %}
                    <span style="color: green;">Оплачено</span>
                {% else %}
                    <a href="{% url 'order_pay' order.id %}">Оплатить</a>
                {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/order_update.html
{% extends 'main/layout.html' %}

{% block content %}
  <h1>Изменить услуги</h1>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="pet">Животное:</label>
      <select name="pet" id="pet">
        {% for pet in pets %}
          <option value="{{ pet.id }}" {% if pet == order.pet %}selected{% endif %}>{{ pet.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="doctor">Доктор:</label>
      <select name="doctor" id="doctor">
        {% for doctor in doctors %}
          <option value="{{ doctor.id }}" {% if doctor == order.doctor %}selected{% endif %}>{{ doctor.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="date">Дата:</label>
      <input type="date" name="date" id="date" value="{{ order.date|date:'Y-m-d' }}">
    </div>
    <div>
      <label>Услуги:</label>
      {% for service in services %}
        <div>
          <input type="checkbox" name="services" value="{{ service.id }}" {% if service in order.services.all %}checked{% endif %}>
          <label>{{ service.name }} - {{ service.cost }}</label>
        </div>
      {% endfor %}
    </div>
    <button type="submit">Обновить информацию об услуге</button>
  </form>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/pay.html
{% extends 'main/layout.html' %}

{% block content %}
<h1>Оплата заказа</h1>
  <p>Дата: {{ order.date }}</p>
  <p>Питомец: {{ order.pet.name }}</p>
  <p>Доктор: {{ order.doctor.name }}</p>
  <p>Услуги:</p>
  <ul>
    {% for service in order.services.all %}
      <li>{{ service.name }} - {{ service.cost }}</li>
    {% endfor %}
  </ul>
    <p>Общая стоимость: {{ order.total_cost }}</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Оплатить</button>
</form>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/service_create.html
{% extends 'main/layout.html' %}

{% block content %}
  <h1>Создание новой услуги</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Сохранить</button>
</form>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/service_delete.html
<!-- service_delete.html -->
{% extends 'main/layout.html' %}

{% block content %}
<h1>Удаление услуги</h1>
<p>Вы уверены, что хотите удалить следующую услугу?</p>
<ul>
  <li>Название: {{ service.name }}</li>
  <li>Стоимость: {{ service.cost }} руб.</li>
</ul>
<form method="post">
  {% csrf_token %}
  <button type="submit">Да, удалить</button>
  <a href="{% url 'service_list' %}">Нет, отмена</a>
</form>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/service_detail.html
{% extends 'main/layout.html' %}

{% block content %}
<h1>Информация об услуге</h1>
<table>
  <tr>
    <th>Название</th>
    <td>{{ service.name }}</td>
  </tr>
  <tr>
    <th>Стоимость</th>
    <td>{{ service.cost }} руб.</td>
  </tr>
  <tr>
    <th>Категория</th>
    <td>{{ service.category.name }}</td>
  </tr>
</table>
{% if user.is_staff %}
<h2>Заказы, в которые входит эта услуга</h2>
<ul>
  {% for order in service.order_set.all %}
  <li>
    <a href="{% url 'order_detail' order.id %}">
      Заказ от {{ order.date }} для клиента {{ order.client.name }}
    </a>
  </li>
  {% empty %}
  <li>Эта услуга пока не входит ни в один заказ.</li>
  {% endfor %}
</ul>

<a href="{% url 'service_update' service.id %}">Изменить</a>
<a href="{% url 'service_delete' service.id %}">Удалить</a>
<a href="{% url 'service_list' %}">Вернуться к списку</a>
{% endif %}
<pre>
  <a href="{% url 'order_create' %}"><b>Добавить в корзину</b></a>
</pre>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/service_list.html
<!-- service_list.html -->
{% extends 'main/layout.html' %}

{% block content %}
{% if user.is_staff %}
  <a href="{% url 'service_create' %}">Добавить новую услугу</a>
{% endif %}
<h1>Список услуг</h1>
<ul>
  {% for service in services %}
  <li>
    <a href="{% url 'service_detail' service.id %}">{{ service.name }} - {{ service.cost }} руб.</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

IGI/LR5/VeterinaryClinc/appointments/templates/service_update.html
<!-- service_update.html -->
{% extends 'main/layout.html' %}

{% block content %}
<h1>Обновление услуги</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Сохранить</button>
</form>
{% endblock %}