IGI/LR5/VeterinaryClinc/VeterinaryClinc/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from VeterinaryClinc import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('clients/', include('clients.urls')),
    path('appointments/', include('appointments.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('articles/', include('chart_django_project.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/VeterinaryClinc/main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('cat_fact', views.cat_fact_view, name='cat_fact'),
    path('random_dog', views.random_dog_view, name='random_dog'),
    path('questions/', views.questions_list, name='questions_list'),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('vacancies/', views.VacancyListView.as_view(), name='vacancy-list'),
    path('vacancies/<int:pk>/', views.VacancyDetailView.as_view(), name='vacancy-detail'),
    path('promocodes/', views.promocode_list, name='promocode-list'),
    path('reviews/', views.reviews_list, name='reviews-list'),
    path('add_review/', views.add_review, name='add_review'),
    path('policy/', views.policy, name='policy'),
    path('partners/', views.partner_list, name='partner_list')
]

IGI/LR5/VeterinaryClinc/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('preregistration/', views.preregistration, name='preregistration'),
    path('registerclient/', views.RegisterClient.as_view(), name='registerclient'),
    path('registerdoctor/', views.RegisterDoctor.as_view(), name='registerdoctor'),
    path('list_doctors/', views.list_doctors, name='list_doctors')
]

IGI/LR5/VeterinaryClinc/appointments/models.py
from asyncio.windows_events import NULL

from django.db import models
from django.db.models import Sum
from django.urls import reverse

from clients.models import Pet
from users.models import Client, Doctor

from main.models import PromoCode


class ServiceCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


class Service(models.Model):
    name = models.CharField(max_length=255)
    cost = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE, related_name='services')


    def __str__(self):
        return f'{self.name} costs {self.cost}'

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='appointments')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='appointments')
    date = models.DateField()
    services = models.ManyToManyField(Service, through='OrderService')
    total_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    is_payed = models.BooleanField(default=False)  # Новое поле
    def __str__(self):
        return f'{self.date}'

    def save(self, *args, **kwargs):
        discount = 1.0
        if self.pk:
            if self.client.promocode:
                try:
                    promo = PromoCode.objects.get(promocode=self.client.promocode)
                    discount = (self.total_cost * promo.percent) / 100
                except PromoCode.DoesNotExist:
                    pass

            self.total_cost = self.services.aggregate(total=Sum('cost'))['total'] or 0.00
            if self.client.promocode is not NULL:
                discount = (self.total_cost * promo.percent) / 100
                self.total_cost -= discount

        super().save(*args, **kwargs)

class OrderService(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

IGI/LR5/VeterinaryClinc/main/models.py
from django.db import models

from VeterinaryClinc import settings


class Questions(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

class PromoCode(models.Model):
    promocode = models.CharField(max_length=50)
    percent = models.IntegerField()



class Vacancy(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateField()

class Partner(models.Model):
    name=models.CharField(max_length=100)
    logo=models.ImageField(upload_to="logos/")
    website=models.URLField()

    def __str__(self):
        return self.name

IGI/LR5/VeterinaryClinc/main/forms.py
from django import forms

from main.models import Questions
from main.models import Review

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ['question']

class AnswerForm(forms.Form):
    answer = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }

IGI/LR5/VeterinaryClinc/main/views.py
import logging

from django.contrib.auth.decorators import login_required
#from django.contrib.sites import requests
from django.shortcuts import render
import requests
from django.utils import timezone
from news.models import Articles
from appointments.models import Service
from main.forms import ReviewForm
from django.views.generic import ListView, DetailView
logging.basicConfig(level=logging.INFO, filename="py_log.log",filemode="w",
                    format="%(asctime)s %(levelname)s %(message)s")

def index(request):
    partners = Partner.objects.all()
    articles = Articles.objects.all()
    services = Service.objects.all()

    lastest_article = latest_article = max(articles, key=lambda article: article.public_date)

    logging.info("вывести страницу main/index.html")
    return render(request, 'main/index.html',  {'lastest_article': lastest_article, 'partners': partners, 'services':services})

@login_required
def about(request):
    logging.info("вывести страницу main/about.html")
    return render(request, "main/about.html")


def get_cat_fact():
    logging.info("Обратиться к стороннему API")
    url = 'https://catfact.ninja/fact'
    try:
        logging.info("Попытка обращения к стороннему API")
        response = requests.get(url)
        # Код 200 означает, что запрос был успешен
        if response.status_code == 200:
            cat_fact_data = response.json()
            return cat_fact_data.get('fact')
        else:
            return None
    except requests.RequestException as e:
        logging.exception("Попытка обращения к стороннему API не удалась")
        print(f"An error occurred: {e}")
        return None


def cat_fact_view(request):
    fact = get_cat_fact()
    return render(request, 'main/cat_fact.html', {'cat_fact': fact})


def get_random_dog_image():
    url = 'https://dog.ceo/api/breeds/image/random'
    try:
        response = requests.get(url)
        if response.status_code == 200:
            dog_data = response.json()
            return dog_data.get('message')  # 'message' содержит URL изображения собаки
        else:
            return None
    except requests.RequestException as e:
        print(f"An error occurred: {e}")
        return None


def random_dog_view(request):
    image_url = get_random_dog_image()
    return render(request, 'main/random_dog.html', {'image_url': image_url})


# views.py

from django.shortcuts import render, get_object_or_404, redirect
from .forms import QuestionForm, AnswerForm
from .models import Questions, Vacancy, PromoCode, Review, Partner


def questions_list(request):
    questions = Questions.objects.all().order_by('-date_added') # Получаем только вопросы без ответов
    return render(request, 'main/questions_list.html', {'questions': questions})


class VacancyListView(ListView):
    model = Vacancy
    template_name = 'main/vacancy_list.html'


class VacancyDetailView(DetailView):
    model = Vacancy
    template_name = 'main/vacancy_detail.html'

def promocode_list(request):
    promocodes = PromoCode.objects.all()  # Получаем все промокоды из базы данных
    return render(request, 'main/promocode_list.html', {'promocodes': promocodes})


def reviews_list(request):
    reviews = Review.objects.all()  # Получаем все отзывы из базы данных
    return render(request, 'main/reviews_list.html', {'reviews': reviews})


def policy(request):
    return render(request, "main/policy.html")


def partner_list(request):
    partners = Partner.objects.all()
    return render(request, "main/index.html", {'partners': partners})


class QuestionDetailView(DetailView):
    logging.info("Details_view")
    model = Questions
    template_name = 'main/question_detail.html'
    context_object_name = 'question'


@login_required
def add_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user  # Получаем текущего пользователя
            review.date = timezone.now().date()  # Устанавливаем текущую дату
            review.save()
            return redirect('reviews-list')
    else:
        form = ReviewForm()

    return render(request, 'main/add_review.html', {'form': form})

IGI/LR5/VeterinaryClinc/main/templates/main/about.html
{% extends 'main/layout.html' %}
<title>{% block title %}О компании{% endblock %}</title>
{% block content %}

<form translate="yes" enctype="multipart/form-data">
    <section>
        <div itemscope itemtype="https://schema.org/Recipe">
            <h2 itemprop="name">Все про нашу компанию</h2>
        </div>

    <div id="company-info">
        <h2 accesskey="t" contenteditable="true" spellcheck="true" dir="ltr">О компании</h2>
    </div>
    </section>
    <a href="#n1" contenteditable="true" translate="yes" style="" title="примечание">См.примечание ниже - описание видов домашних животных</a>
    <section>
        <h3 hidden="hidden">Расскажите про покупки</h3>
    <div id="video">
        <h2>Видео</h2>
        <video width="640" height="360" controls preload="none" muted>
            <source itemprop="video" src="static/main/vid/cat.mp4" type="video/mp4">
            Ваш браузер не поддерживает видео.
        </video>
    </div>
    </section>
    <section title="аудио">
    <div id="audio">
        <h2>Аудио</h2>
        <audio controls>
            <source itemprop="audio" src="static/main/audio/dogCanBeBiter.mp3" type="audio/mpeg">

            Ваш браузер не поддерживает аудио.
        </audio>
    </div>
    </section>
    <section>
    <div id="logo">
        <h2>Логотип</h2>
        <img itemprop="logo" src="static/main/img/logo.png" alt="Логотип компании">
    </div>
    </section>
    <section>
    <article id="history">
        <h2>История по годам</h2>
        <ul itemprop="history">
            <li>2000: Основание компании</li>
            <li>2005: Запуск первого продукта</li>
            <li>2010: Расширение на международные рынки</li>
            <li>2015: Получение наград за качество</li>
            <li>2020: Цифровая трансформация</li>
        </ul>
    </article>
    </section>
    <section>
    <article id="contact-info">
        <h2>Реквизиты</h2>
        <p>Название компании: Пример ООО</p>
        <p>ИНН: 1234567890</p>
        <p>КПП: 123456789</p>
        <p>ОГРН: 1234567890123</p>
        <p>Юридический адрес: г. Москва, ул. Примерная, д. 1</p>
    </article>
    </section>
    <blockquote cite="http://en.wikipedia.org/wiki/Apple">
Домашнее млекопитающее животное из сем., к к-рому относятся также тигр, лев и т. п.
"Кошка истребляет мышей и крыс"</blockquote>

    <section>
    <div id="certificate">
        <fieldset>
            <legend>Сертификат:</legend>
            <h1>Сертификат качества ISO</h1>
    <h2>Ветеринарная клиника DOG&CAT</h2>

    <p>Настоящим подтверждается, что ветеринарная клиника DOG&CAT успешно прошла аудит и соответствует требованиям международного стандарта ISO 9001:2015 в области управления качеством.</p>

    <p><strong>Данный сертификат подтверждает, что:</strong></p>
    <ul>
        <li>Ветеринарная клиника обеспечивает высококачественное медицинское обслуживание животных.</li>
        <li>Все процессы клиники направлены на удовлетворение потребностей клиентов и их питомцев.</li>
        <li>В клинике внедрены современные методы диагностики и лечения, а также системы контроля качества.</li>
        <li>Персонал клиники проходит регулярное обучение и повышение квалификации, что гарантирует высокий уровень профессионализма и заботы о пациентах.</li>
        <li>Клиника соблюдает все необходимые стандарты безопасности и гигиены.</li>
    </ul>

    <p><strong>Выдано:</strong> 18.09.2024</p>
    <p><strong>Срок действия:</strong> 18.09.2025</p>
    <p><strong>Номер сертификата:</strong>24761249301</p>

    <div class="signature">
        <p><strong>Подпись:</strong>
        <img src="static/main/img/signature.png" alt="Подпись" align="center" width="200">
        Власенко И.И.</p>

        </div>
        </fieldset>

        </div>
        </section>
    <section>
    <h3>Листинг кода:</h3>
    <pre>
    <code>class Review(models.Model):
        <var>user</var> = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
        <var>rating</var> = models.IntegerField()
        <var>text</var> = models.TextField()
        <var>date</var> = models.DateField()</code>
    </pre>

    <h3>Сокращения</h3>
    <abbr title="Современные технологии разработки web-приложений">СТРweb-пр</abbr>
    <br>
    <h3>Определения</h3>
    Интерфейс в C# - это набор <dfn title="Сигнатура состоит из имени метода и его параметров">сигнатур</dfn> методов.
    <h3>Цитаты</h3>
    <q cite="https://metanit.com/sharp/tutorial/17.1.php">По умолчанию все элементы коллекции в <mark>LINQ</mark> обрабатываются последовательно, но начиная с .NET 4.0 в пространство имен System.Linq был добавлен класс ParallelEnumerable, который инкапсулирует функциональность PLINQ (Parallel LINQ) и позволяет выполнять обращения к коллекции в параллельном режиме.</q>
    <blockquote cite="https://ru.wikipedia.org/wiki/%D0%A6%D0%B8%D1%82%D0%B0%D1%82%D0%B0#:~:text=%D0%A6%D0%B8%D1%82%D0%B0%CC%81%D1%82%D0%B0%20(%D0%BE%D1%82%20%D0%BB%D0%B0%D1%82.,%D0%B4%D0%BB%D1%8F%20%D0%BA%D1%80%D0%B8%D1%82%D0%B8%D0%BA%D0%B8%20%D1%81%D0%B0%D0%BC%D0%BE%D0%B9%20%D1%86%D0%B8%D1%82%D0%B8%D1%80%D1%83%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BC%D1%8B%D1%81%D0%BB%D0%B8.">Цитата</blockquote>
    <h3>Дата и время:</h3>


    <center><h3>Важное стихотворение:</h3>

    <i><font size="5" color="red" face="Arial">Б</font>еспокойно бегал <wbr>по дороге пёсик —<br>
То ли потерялся,<wbr> то ли кто-то бросил.<br>
Бегал и поскуливал<wbr> грустно и отчаянно,<br>
Отыскать пытался он<wbr> своего хозяина.<br>
<br>
Жаль, что не умел он <wbr>всё сказать словами,<br>
Лишь глаза блестели<wbr> пёсьими слезами.<br>
Помогите, люди, тем,<wbr> кто другом брошен.<br>
        Не должно бездомных быть <wbr>ни собак, ни кошек.<br></i></center>



    <p><a id="n1"></a>Далее будут описаны виды:</p>
    <pre>Виды домашних животных и их классификация
Домашние животные — это животные, которые были одомашнены и живут рядом с человеком. Они играют важную роль в жизни людей, выполняя различные функции, от companionship (компаньонов) до помощи в хозяйстве. Классификация домашних животных может быть выполнена по нескольким критериям, включая вид, назначение и поведение.

Основные виды домашних животных</pre>
        <li type="A" >Собаки</li>
        <ul>
            <li>Описание: Собаки — одни из самых популярных домашних животных. Они известны своей преданностью и разнообразием пород, каждая из которых имеет свои характеристики и особенности.</li>
            <li>Классификация: Собаки могут быть классифицированы по размерам (малые, средние и большие), по рабочим качествам (пастушьи, охотничьи, служебные) и по темпераменту (активные, спокойные, защитные).</li>
        </ul>

        <div style="width:100%">
            <picture>
                <source media="(max-width: 1000px)"
                    sizes="(max-width: 500px) 50vw, 10vw"
                    srcset="static/main/img/dog.jpg 1500w">
                 <source media="(max-width: 3500px)"
                    sizes="(max-width: 2500px) 50vw, 10vw"
                    srcset="static/main/img/dog1.jpg 500w">
                <img src="static/main/img/dog2.jpg" alt="собака">
            </picture>
        </div>


        <li type="A" >Кошки</li>
    <figure>
        <figcaption>Кошки - мои любимые животные</figcaption>
        <ul>
            <li>Описание: Кошки — независимые и грациозные животные, которые также являются популярными компаньонами. Они известны своим игривым поведением и охотничьими инстинктами.</li>
            <li>Классификация: Кошки могут быть краткошерстными и длинношерстными, а также по породам (персидские, сиамские, британские).</li>
        </ul>
         <img src="static/main/img/cat.jpg" width="300" alt="Cat">
    </figure>
        <li type="A" >Грызуны</li>
        <ul>
            <li>Описание: Грызуны, такие как хомяки, морские свинки и крысы, становятся все более популярными в качестве домашних животных. Они требуют меньшего ухода по сравнению с собаками и кошками.</li>
            <li>Классификация: Грызуны могут быть разделены на домашних и диких, а также по размерам (маленькие и средние).</li>
        </ul>
        <img src="static/main/img/griz.jpg" width="300" alt="Грызун">
        <li type="A" >Птицы</li>
        <ul>
            <li>Описание: Многие люди держат птиц, таких как попугаи, канарейки и воробьи, в качестве домашних животных. Птицы могут быть очень общительными и способны обучаться.</li>
            <li>Классификация: Птицы могут быть классифицированы по размеру (малые, средние, большие) и по способности к обучению (говорящие и неговорящие).</li>
        </ul>
        <img src="static/main/img/bird.jpg" width="300" alt="Птица">
        <li type="A" >Рептилии</li>
        <ul>
            <li>Описание: Рептилии, такие как ящерицы, змеи и черепахи, становятся все более популярными среди любителей экзотических животных. Они требуют специфических условий содержания.</li>
            <li>Классификация: Рептилии могут быть разделены на ядовитых и неядовитых, а также по среде обитания (сухопутные и водные).</li>
        </ul>
        <img src="static/main/img/reptil.jpg" alt="Рептилия" width="300">

    <br>
    <br>

        <table border="1" summary="Соотношение животных" >
        <caption>Соотношение животных в процентах по месту жительства</caption>
            <thead>
        <tr>

            <th id="category">Категория</th>
            <th id="dogs">Собаки(%)</th>
            <th id="cats">Коты(%)</th>
            <th rowspan="5" id="Pets">Pets</th>
        </tr>
        </thead>
            <tbody>
        <tr>
            <th headers="category">Забирают из приюта</th>
            <td>60</td>
            <td>50</td>
        </tr>
        <tr>
            <th headers="category">Остаются в приюте</th>
            <td>20</td>
            <td>30</td>
        </tr>
        <tr>
            <th headers="category">Живут у волонтеров</th>
            <td colspan="2">15</td>
        </tr>
        <tr>
            <th headers="category">Живут на улицах</th>
            <td colspan="2" >5</td>
        </tr>
            </tbody>
    </table>
    <br>
    <p>Выбрать себе любимца можно, например, на этих сайтах:</p>
        <ul>
    <li>
      <a href="https://superkot.by/" target="fr">Приют для животных Суперкот</a>
    </li>
    <li>
      <a href="https://zooshans.by/" target="fr">Приют для животных ЗООшанс</a>
    </li>
  </ul>
  <iframe name="fr" width="1500" height="500">Old browser</iframe>
</section>
</form>
    Дата и время создания сайта:
    <time datetime="13:38">13:38</time>
    <time datetime="2024-09-18">18 сентября</time>
{% endblock %}

IGI/LR5/VeterinaryClinc/main/templates/main/add_review.html
{% extends 'main/layout.html' %}
{% block title %}<h1>Добавить отзыв</h1>{% endblock %}

{% block content %}
<h1>Добавить отзыв</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

IGI/LR5/VeterinaryClinc/main/templates/main/cat_fact.html
{% extends 'main/layout.html' %}
{% block title %}<h1>Рубрика рандомные факты о кошках</h1>{% endblock %}

{% block content %}
  <h1>Рубрика рандомные факты о кошках</h1>
{% if cat_fact %}
  <p>Random Cat Fact: {{ cat_fact }}</p>
{% else %}
  <p>Sorry, we couldn't load a cat fact right now.</p>
{% endif %}

{% endblock %}

IGI/LR5/VeterinaryClinc/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block content %}
<form enctype="multipart/form-data">
    <div class="features">
        <h1>Главная страница</h1>
        <img src="static/main/img/logo.png" alt="Logo">
        <img src="static/main/img/banner1.jpg" alt="banner1">

        <h4>Ветеринарная клиника Друг в Минске </h4>

        <h1 translate="yes">{{ lastest_article.title }}</h1>
        <p><strong>Анонс:</strong> {{ lastest_article.anons }}</p>
        <p><strong>Полный текст:</strong> {{ lastest_article.full_text }}</p>
        <p><strong>Дата публикации:</strong> {{ lastest_article.public_date }}</p>

        <h2>Список услуг</h2>
        <ul>
            {% for service in services %}
            <li>
                <a href="{% url 'service_detail' service.id %}">{{ service.name }} - {{ service.cost }} руб.</a>
            </li>
            {% endfor %}
        </ul>
        <h2>Компании-партнеры</h2>
        <table>
            <thead>
                <tr>
                    <th>Логотип</th>
                    <th>Название</th>
                    <th>Сайт</th>
                </tr>
            </thead>
            <tbody>
                {% for partner in partners %}
                    <tr>
                        <td><img src="{{ partner.logo.url }}" alt="{{ partner.name }}" style="max-width: 100px;"></td>
                        <td>{{ partner.name }}</td>
                        <td><a href="{{ partner.website }}">{{ partner.website }}</a></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">Нет партнеров.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</form>
{% endblock %}

IGI/LR5/VeterinaryClinc/main/templates/main/layout.html
{% load static %}
<html lang="ru">
<head>
    <base target="_self">
    <meta charset="UTF-8">
    <meta   name="author"
            content="Veronika Yarmak">
    <title>{% block title %}Главная{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'main/icons/icon.png' %}" type="image/x-icon" />
</head>
<body>
<address>Created by Yarmak Veronika 253503</address>
            <fieldset title="Nav">
            <legend><h3>Навигация</h3></legend>
        <nav>
            {% if user.is_authenticated %}
                <span class="last"> {{user.username}} | <a href="{% url 'users:logout' %} ">Выйти</a></span>
            {% else %}
                <span class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:preregistration' %}">Регистрация</a></span>
            {% endif %}
            <br>
            <span><a href="{% url 'home' %}"><i class="fas fa-home"></i>Главная</a></span>
            <span> | <a href="{% url 'about' %}"><i class="fas fa-address-card"></i>О компании</a></span>
            <span> | <a href="{% url 'news_home' %}"><i class="fas fa-paper-plane"></i>Новости</a></span>
            {% if user.is_staff %}
                <span> | <a href="{% url 'doctors_schedule' %}">Расписание</a></span>
            {% else %}
                <span> | <a href="{% url 'clients_home' %}">Питомцы</a></span>
                <span> | <a href="{% url 'order_list' %}">Корзина заказов</a></span>
            {% endif %}
            <span> | <a href="{% url 'service_list' %}">Услуги</a></span>
            <span> | <a href="{% url 'questions_list' %}">Словарь терминов и понятий</a></span>
            <span> | <a href="{% url 'users:list_doctors' %}">Контакты</a></span>
            <span> | <a href="{% url 'policy' %}">Политика</a></span>
            <span> | <a href="{% url 'vacancy-list' %}">Вакансии</a></span>
            <span> | <a href="{% url 'reviews-list' %}">Отзывы</a></span>
            <span> | <a href="{% url 'promocode-list' %}">Промокоды и купоны</a></span>
            <span> | <a href="{% url 'statistics' %}">Статистика</a></span>
            <span> | <a href="{% url 'article-index' %}">График</a></span>

        </nav>
            </fieldset>
        <hr color="darkgreen" size="3">
            <nav>
            <li><a href="{% url 'cat_fact' %}">Факты о кошках</a></li>
            <li><a href="{% url 'random_dog' %}">Фотографии собак</a></li>
            </nav>
        <hr color="darkgreen" size="3">
    <main>
        {% block content %}
        {%  endblock %}
    </main>
</body>
<footer>
    <h4>Полезные ссылки:</h4>
    <a href="mailto:veroni.rmk@gmail.com?subject=Вопрос">Вопрос на почту клиники</a> |
    <a href="tel:+375445788672">Активный номер телефона</a> |
    <a download="static/main/img/Sertificate.png" href="static/main/img/Sertificate.png">Ссылка для скачивания сертификатов</a> |
    <a rel="nofollow" target="_blank" href="https://zooshans.by/">Сайт партнеров</a>
    <br>
    <br>
    <div class="container">
        <span class="text-muted">© 2024 Ветеринарная клиника</span>
    </div>
</footer>
</html>

IGI/LR5/VeterinaryClinc/main/templates/main/promocode_list.html
{% extends 'main/layout.html' %}

{% block content %}
  <h2>Список промокодов</h2>
  <table>
    <thead>
      <tr>
        <th>Промокод</th>
        <th>Процент скидки</th>
      </tr>
    </thead>
    <tbody>
      {% for promo in promocodes %}
        <tr>
          <td>{{ promo.promocode }}</td>
          <td>{{ promo.percent }}%</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="2">Нет доступных промокодов.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

IGI/LR5/VeterinaryClinc/main/templates/main/question_detail.html
{% extends 'main/layout.html' %}

{% block title %}<h1>{{ article.title }}</h1>{% endblock %}

{% block content %}
<form enctype="multipart/form-data">
    <div class="features">

        <h1>{{ question.question }}</h1>
        <p>{{  question.answer }}</p>
        <p>{{ question.date_added }}</p>
    </div>
</form>
{% endblock %}

IGI/LR5/VeterinaryClinc/main/templates/main/test.html
<p>Просто проверка</p>